import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";
import ModalLogin from "@/components/ModalLogin/ModalLogin";
import RegModal from "@/components/RegModal/RegModal";
import Cart from "@/components/Cart/Cart";
import ModalAddedProduct from "@/components/ModalAddedProduct/ModalAddedProduct";
import CallModal from "@/components/CallModal/CallModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <ModalLogin />
          <RegModal />
          <Cart />
          <ModalAddedProduct />
          <CallModal />
          {children}
        </Providers>
      </body>
    </html>
  );
}
